M48
; DRILL file {KiCad (6.0.5-0)} date Saturday, 04 June 2022 at 20:41:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-04T20:41:55+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X140.86Y-103.895
X165.77Y-94.91
X165.77Y-114.61
T2
X136.0Y-112.0
X148.0Y-99.23
T0
M30
